In [ ]:
import pandas as pd
import numpy as np

print("Dataset Cleaning & Preprocessing Task 1.2 Started Successfully!")

Dataset Cleaning & Preprocessing Task 1.2 Started Successfully!

In [6]:
df = pd.read_csv('/content/student_performance_raw.csv')

df.head()

   Student_ID     Name  Gender Department   Age  Marks Attendance        City
0         101     Arun    Male    AI & DS  19.0   85.0        92%     Chennai
1         102   Priya   Female   AI & DS   20.0   92.0        88%     Chennai
2         103  Karthik    Male        CSE  19.0    NaN        95%  Coimbatore
3         104    Meena  Female    AI & DS  20.0   78.0        90%     Chennai
4         105     Arun    Male        CSE  19.0   85.0        92%     Chennai

In [7]:
df.isnull().sum()

Student_ID    0
Name          0
Gender        0
Department    0
Age           1
Marks         2
Attendance    0
City          0
dtype: int64

In [8]:
df['Age'] = df['Age'].fillna(df['Age'].median())
df['Marks'] = df['Marks'].fillna(df['Marks'].median())

print("Missing values handled successfully!")

Missing values handled successfully!

In [9]:
print("Duplicate rows:", df.duplicated().sum())

Duplicate rows: 2

In [10]:
df = df.drop_duplicates()

print("Duplicate rows removed successfully!")
print("Remaining rows:", len(df))

Duplicate rows removed successfully!
Remaining rows: 12

In [11]:
# Remove extra spaces
df['Name'] = df['Name'].str.strip()
df['Gender'] = df['Gender'].str.strip().str.title()
df['Department'] = df['Department'].str.strip().str.upper()
df['City'] = df['City'].str.strip().str.title()

print("Inconsistent formatting cleaned successfully!")
print("\nCleaned formatting preview:")
print(df[['Name', 'Gender', 'Department', 'City']].head())

Inconsistent formatting cleaned successfully!

Cleaned formatting preview:
      Name  Gender Department        City
0     Arun    Male    AI & DS     Chennai
1    Priya  Female    AI & DS     Chennai
2  Karthik    Male        CSE  Coimbatore
3    Meena  Female    AI & DS     Chennai
4     Arun    Male        CSE     Chennai

In [12]:
df['Attendance'] = df['Attendance'].str.replace('%', '', regex=False).astype(float)

print("Attendance column cleaned successfully!")
print(df[['Student_ID', 'Attendance']].head())

Attendance column cleaned successfully!
   Student_ID  Attendance
0         101        92.0
1         102        88.0
2         103        95.0
3         104        90.0
4         105        92.0

In [13]:
print("Final Dataset Information:")
print(df.info())

print("\nMissing Values:")
print(df.isnull().sum())

print("\nDuplicate Rows:")
print(df.duplicated().sum())

Final Dataset Information:
<class 'pandas.core.frame.DataFrame'>
Index: 12 entries, 0 to 11
Data columns (total 8 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   Student_ID  12 non-null     int64
 1   Name        12 non-null     object
 2   Gender      12 non-null     object
 3   Department  12 non-null     object
 4   Age         12 non-null     float64
 5   Marks       12 non-null     float64
 6   Attendance  12 non-null     float64
 7   City        12 non-null     object
dtypes: float64(3), int64(1), object(4)
memory usage: 864.0+ bytes
None

Missing Values:
Student_ID    0
Name          0
Gender        0
Department    0
Age           0
Marks         0
Attendance    0
City          0
dtype: int64

Duplicate Rows:
0

In [14]:
df.to_csv('student_performance_cleaned.csv', index=False)

print("Cleaned dataset saved successfully!")
print("File name: student_performance_cleaned.csv")

Cleaned dataset saved successfully!
File name: student_performance_cleaned.csv